### ISSUE TITLE
Thumbnail noch falsch

### ISSUE THREAD

**Issue by McWizard** [BCRM/www-content#4]
![bcrm14](https://cloud.githubusercontent.com/assets/820537/9378463/eedc96f8-4721-11e5-9cc8-ea7d888cd2ce.png)

Ich weiß nicht genau, wo es herkommt, aber es ist falsch :)

**Comment by coderbyheart** [comment]
Von da https://github.com/BCRM/www/blob/master/src/BCRM/WebBundle/Resources/public/images/bcrm.jpg @martinkraft kannst Du mal eine neue Version bauen?

**Comment by McWizard** [comment]
Man beachte: Der Text ist auch auf 2014 aber mit richtigem Tag+Monat...

**Comment by coderbyheart** [comment]
Ja, das ist schon richtig. Der Text kommt ja aus der Config.
